--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28.12.2023 18:09:41
-- Server version: 8.0.31
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE smartmarketdb;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop table `product`
--
DROP TABLE IF EXISTS product;

--
-- Drop table `sales`
--
DROP TABLE IF EXISTS sales;

--
-- Drop table `supermarket`
--
DROP TABLE IF EXISTS supermarket;

--
-- Drop table `category`
--
DROP TABLE IF EXISTS category;

--
-- Set default database
--
USE smartmarketdb;

--
-- Create table `category`
--
CREATE TABLE category (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 105,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `supermarket`
--
CREATE TABLE supermarket (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `sales`
--
CREATE TABLE sales (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  date DATETIME(6) DEFAULT NULL,
  cost FLOAT DEFAULT NULL,
  productlist VARCHAR(255) DEFAULT NULL,
  supermarket_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE sales 
  ADD CONSTRAINT FK_sales_supermarket_id FOREIGN KEY (supermarket_id)
    REFERENCES supermarket(id);

--
-- Create table `product`
--
CREATE TABLE product (
  id VARCHAR(255) NOT NULL,
  name VARCHAR(255) DEFAULT NULL,
  price FLOAT DEFAULT NULL,
  expirationDate DATE DEFAULT NULL,
  `count` INT NOT NULL DEFAULT 0,
  supermarket_id INT UNSIGNED NOT NULL,
  category_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `UK_product_id` on table `product`
--
ALTER TABLE product 
  ADD UNIQUE INDEX UK_product_id(id);

--
-- Create foreign key
--
ALTER TABLE product 
  ADD CONSTRAINT FK_product_category_id FOREIGN KEY (category_id)
    REFERENCES category(id) ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE product 
  ADD CONSTRAINT FK_product_supermarket_id FOREIGN KEY (supermarket_id)
    REFERENCES supermarket(id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `employee`
--
CREATE TABLE employee (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  education VARCHAR(255) DEFAULT NULL,
  post ENUM('Cashier','Cleaner','Loader','Manager','Merchandiser','Security') DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  supermarket_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10009,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE employee 
  ADD CONSTRAINT FK_employee_supermarket_id FOREIGN KEY (supermarket_id)
    REFERENCES supermarket(id) ON UPDATE CASCADE;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;