package stu.cn.ua.view.panels;

import stu.cn.ua.model.PostsENUM;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class EmployeesPanel {
    private JPanel employeesPanel;
    private JTable table;
    private JTextField searchTextField;
    private JButton searchButton;
    private JScrollPane tablePane;
    private JButton cancelButton;
    private JComboBox<PostsENUM> postComboBox;
    private JLabel searchLabel;

    public EmployeesPanel() {
        $$$setupUI$$$();
        postComboBox.addItem(PostsENUM.Manager);
        postComboBox.addItem(PostsENUM.Cashier);
        postComboBox.addItem(PostsENUM.Merchandiser);
        postComboBox.addItem(PostsENUM.Loader);
        postComboBox.addItem(PostsENUM.Security);
        postComboBox.addItem(PostsENUM.Cleaner);
    }

    public JPanel getEmployeesPanel() {
        return employeesPanel;
    }

    public JLabel getSearchLabel() {
        return searchLabel;
    }

    public JComboBox<PostsENUM> getPostComboBox() {
        return postComboBox;
    }

    public JButton getCancelButton() {
        return cancelButton;
    }

    public JTable getTable() {
        return table;
    }

    public JTextField getSearchTextField() {
        return searchTextField;
    }

    public JButton getSearchButton() {
        return searchButton;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        employeesPanel = new JPanel();
        employeesPanel.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridheight = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 10;
        employeesPanel.add(spacer1, gbc);
        searchLabel = new JLabel();
        searchLabel.setAutoscrolls(true);
        Font searchLabelFont = this.$$$getFont$$$("Consolas", Font.PLAIN, 16, searchLabel.getFont());
        if (searchLabelFont != null) searchLabel.setFont(searchLabelFont);
        searchLabel.setText("Enter name or login");
        searchLabel.setVisible(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        employeesPanel.add(searchLabel, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        employeesPanel.add(spacer2, gbc);
        searchTextField = new JTextField();
        Font searchTextFieldFont = this.$$$getFont$$$("Consolas", Font.PLAIN, 16, searchTextField.getFont());
        if (searchTextFieldFont != null) searchTextField.setFont(searchTextFieldFont);
        searchTextField.setMargin(new Insets(3, 8, 3, 8));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        employeesPanel.add(searchTextField, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        employeesPanel.add(spacer3, gbc);
        searchButton = new JButton();
        Font searchButtonFont = this.$$$getFont$$$("Consolas", Font.PLAIN, 16, searchButton.getFont());
        if (searchButtonFont != null) searchButton.setFont(searchButtonFont);
        searchButton.setText("Search");
        searchButton.setVisible(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        employeesPanel.add(searchButton, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        employeesPanel.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 10;
        employeesPanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        employeesPanel.add(spacer6, gbc);
        tablePane = new JScrollPane();
        tablePane.setPreferredSize(new Dimension(450, 400));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 8;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        employeesPanel.add(tablePane, gbc);
        tablePane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        table = new JTable();
        table.setEnabled(true);
        Font tableFont = this.$$$getFont$$$("Consolas", Font.PLAIN, 16, table.getFont());
        if (tableFont != null) table.setFont(tableFont);
        table.setRowHeight(35);
        tablePane.setViewportView(table);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        employeesPanel.add(spacer7, gbc);
        cancelButton = new JButton();
        cancelButton.setEnabled(true);
        Font cancelButtonFont = this.$$$getFont$$$("Consolas", Font.PLAIN, 16, cancelButton.getFont());
        if (cancelButtonFont != null) cancelButton.setFont(cancelButtonFont);
        cancelButton.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        employeesPanel.add(cancelButton, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        employeesPanel.add(spacer8, gbc);
        postComboBox = new JComboBox();
        Font postComboBoxFont = this.$$$getFont$$$("Consolas", Font.PLAIN, 16, postComboBox.getFont());
        if (postComboBoxFont != null) postComboBox.setFont(postComboBoxFont);
        postComboBox.setPreferredSize(new Dimension(120, 35));
        postComboBox.setVisible(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        employeesPanel.add(postComboBox, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return employeesPanel;
    }

}
